// Code generated by ent, DO NOT EDIT.

package redeemcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the redeemcode type in the database.
	Label = "redeem_code"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldValue holds the string denoting the value field in the database.
	FieldValue = "value"
	// FieldMaxRedemptions holds the string denoting the max_redemptions field in the database.
	FieldMaxRedemptions = "max_redemptions"
	// FieldRedeemedCount holds the string denoting the redeemed_count field in the database.
	FieldRedeemedCount = "redeemed_count"
	// FieldPerUserLimit holds the string denoting the per_user_limit field in the database.
	FieldPerUserLimit = "per_user_limit"
	// FieldRandomAmountEnabled holds the string denoting the random_amount_enabled field in the database.
	FieldRandomAmountEnabled = "random_amount_enabled"
	// FieldRandomMinValue holds the string denoting the random_min_value field in the database.
	FieldRandomMinValue = "random_min_value"
	// FieldRandomMaxValue holds the string denoting the random_max_value field in the database.
	FieldRandomMaxValue = "random_max_value"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldUsedBy holds the string denoting the used_by field in the database.
	FieldUsedBy = "used_by"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUsedAt holds the string denoting the used_at field in the database.
	FieldUsedAt = "used_at"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeGroup holds the string denoting the group edge name in mutations.
	EdgeGroup = "group"
	// EdgeUsages holds the string denoting the usages edge name in mutations.
	EdgeUsages = "usages"
	// Table holds the table name of the redeemcode in the database.
	Table = "redeem_codes"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "redeem_codes"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "used_by"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "redeem_codes"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "created_by"
	// GroupTable is the table that holds the group relation/edge.
	GroupTable = "redeem_codes"
	// GroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	GroupInverseTable = "groups"
	// GroupColumn is the table column denoting the group relation/edge.
	GroupColumn = "group_id"
	// UsagesTable is the table that holds the usages relation/edge.
	UsagesTable = "redeem_code_usages"
	// UsagesInverseTable is the table name for the RedeemCodeUsage entity.
	// It exists in this package in order to avoid circular dependency with the "redeemcodeusage" package.
	UsagesInverseTable = "redeem_code_usages"
	// UsagesColumn is the table column denoting the usages relation/edge.
	UsagesColumn = "redeem_code_id"
)

// Columns holds all SQL columns for redeemcode fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldType,
	FieldValue,
	FieldMaxRedemptions,
	FieldRedeemedCount,
	FieldPerUserLimit,
	FieldRandomAmountEnabled,
	FieldRandomMinValue,
	FieldRandomMaxValue,
	FieldStatus,
	FieldUsedBy,
	FieldCreatedBy,
	FieldUsedAt,
	FieldNotes,
	FieldCreatedAt,
	FieldExpiresAt,
	FieldGroupID,
	FieldValidityDays,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// DefaultType holds the default value on creation for the "type" field.
	DefaultType string
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultValue holds the default value on creation for the "value" field.
	DefaultValue float64
	// DefaultMaxRedemptions holds the default value on creation for the "max_redemptions" field.
	DefaultMaxRedemptions int
	// DefaultRedeemedCount holds the default value on creation for the "redeemed_count" field.
	DefaultRedeemedCount int
	// DefaultPerUserLimit holds the default value on creation for the "per_user_limit" field.
	DefaultPerUserLimit bool
	// DefaultRandomAmountEnabled holds the default value on creation for the "random_amount_enabled" field.
	DefaultRandomAmountEnabled bool
	// DefaultRandomMinValue holds the default value on creation for the "random_min_value" field.
	DefaultRandomMinValue float64
	// DefaultRandomMaxValue holds the default value on creation for the "random_max_value" field.
	DefaultRandomMaxValue float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
)

// OrderOption defines the ordering options for the RedeemCode queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByValue orders the results by the value field.
func ByValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValue, opts...).ToFunc()
}

// ByMaxRedemptions orders the results by the max_redemptions field.
func ByMaxRedemptions(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRedemptions, opts...).ToFunc()
}

// ByRedeemedCount orders the results by the redeemed_count field.
func ByRedeemedCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemedCount, opts...).ToFunc()
}

// ByPerUserLimit orders the results by the per_user_limit field.
func ByPerUserLimit(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPerUserLimit, opts...).ToFunc()
}

// ByRandomAmountEnabled orders the results by the random_amount_enabled field.
func ByRandomAmountEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRandomAmountEnabled, opts...).ToFunc()
}

// ByRandomMinValue orders the results by the random_min_value field.
func ByRandomMinValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRandomMinValue, opts...).ToFunc()
}

// ByRandomMaxValue orders the results by the random_max_value field.
func ByRandomMaxValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRandomMaxValue, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByUsedBy orders the results by the used_by field.
func ByUsedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedBy, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUsedAt orders the results by the used_at field.
func ByUsedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsedAt, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByGroupField orders the results by group field.
func ByGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsagesCount orders the results by usages count.
func ByUsagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newUsagesStep(), opts...)
	}
}

// ByUsages orders the results by usages terms.
func ByUsages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(GroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, GroupTable, GroupColumn),
	)
}
func newUsagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, UsagesTable, UsagesColumn),
	)
}
