// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributorrewardlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ContributorRewardLogUpdate is the builder for updating ContributorRewardLog entities.
type ContributorRewardLogUpdate struct {
	config
	hooks    []Hook
	mutation *ContributorRewardLogMutation
}

// Where appends a list predicates to the ContributorRewardLogUpdate builder.
func (_u *ContributorRewardLogUpdate) Where(ps ...predicate.ContributorRewardLog) *ContributorRewardLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *ContributorRewardLogUpdate) SetRequestID(v string) *ContributorRewardLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableRequestID(v *string) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ContributorRewardLogUpdate) SetAPIKeyID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableAPIKeyID(v *int64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ContributorRewardLogUpdate) AddAPIKeyID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ContributorRewardLogUpdate) SetOwnerUserID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableOwnerUserID(v *int64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (_u *ContributorRewardLogUpdate) SetConsumerUserID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.ResetConsumerUserID()
	_u.mutation.SetConsumerUserID(v)
	return _u
}

// SetNillableConsumerUserID sets the "consumer_user_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableConsumerUserID(v *int64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetConsumerUserID(*v)
	}
	return _u
}

// AddConsumerUserID adds value to the "consumer_user_id" field.
func (_u *ContributorRewardLogUpdate) AddConsumerUserID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.AddConsumerUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ContributorRewardLogUpdate) SetAccountID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableAccountID(v *int64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ContributorRewardLogUpdate) SetGroupID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableGroupID(v *int64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ContributorRewardLogUpdate) AddGroupID(v int64) *ContributorRewardLogUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ContributorRewardLogUpdate) ClearGroupID() *ContributorRewardLogUpdate {
	_u.mutation.ClearGroupID()
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *ContributorRewardLogUpdate) SetTotalCost(v float64) *ContributorRewardLogUpdate {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableTotalCost(v *float64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *ContributorRewardLogUpdate) AddTotalCost(v float64) *ContributorRewardLogUpdate {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *ContributorRewardLogUpdate) SetActualCost(v float64) *ContributorRewardLogUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableActualCost(v *float64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *ContributorRewardLogUpdate) AddActualCost(v float64) *ContributorRewardLogUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (_u *ContributorRewardLogUpdate) SetRewardMultiplier(v float64) *ContributorRewardLogUpdate {
	_u.mutation.ResetRewardMultiplier()
	_u.mutation.SetRewardMultiplier(v)
	return _u
}

// SetNillableRewardMultiplier sets the "reward_multiplier" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableRewardMultiplier(v *float64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetRewardMultiplier(*v)
	}
	return _u
}

// AddRewardMultiplier adds value to the "reward_multiplier" field.
func (_u *ContributorRewardLogUpdate) AddRewardMultiplier(v float64) *ContributorRewardLogUpdate {
	_u.mutation.AddRewardMultiplier(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ContributorRewardLogUpdate) SetRewardAmount(v float64) *ContributorRewardLogUpdate {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ContributorRewardLogUpdate) SetNillableRewardAmount(v *float64) *ContributorRewardLogUpdate {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ContributorRewardLogUpdate) AddRewardAmount(v float64) *ContributorRewardLogUpdate {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ContributorRewardLogUpdate) SetOwnerID(id int64) *ContributorRewardLogUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ContributorRewardLogUpdate) SetOwner(v *User) *ContributorRewardLogUpdate {
	return _u.SetOwnerID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ContributorRewardLogUpdate) SetAccount(v *Account) *ContributorRewardLogUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ContributorRewardLogMutation object of the builder.
func (_u *ContributorRewardLogUpdate) Mutation() *ContributorRewardLogMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ContributorRewardLogUpdate) ClearOwner() *ContributorRewardLogUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ContributorRewardLogUpdate) ClearAccount() *ContributorRewardLogUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContributorRewardLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContributorRewardLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContributorRewardLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContributorRewardLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContributorRewardLogUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := contributorrewardlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ContributorRewardLog.request_id": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ContributorRewardLog.owner"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ContributorRewardLog.account"`)
	}
	return nil
}

func (_u *ContributorRewardLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contributorrewardlog.Table, contributorrewardlog.Columns, sqlgraph.NewFieldSpec(contributorrewardlog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(contributorrewardlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(contributorrewardlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(contributorrewardlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConsumerUserID(); ok {
		_spec.SetField(contributorrewardlog.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConsumerUserID(); ok {
		_spec.AddField(contributorrewardlog.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(contributorrewardlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(contributorrewardlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(contributorrewardlog.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(contributorrewardlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(contributorrewardlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(contributorrewardlog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(contributorrewardlog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardMultiplier(); ok {
		_spec.SetField(contributorrewardlog.FieldRewardMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardMultiplier(); ok {
		_spec.AddField(contributorrewardlog.FieldRewardMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(contributorrewardlog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(contributorrewardlog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.OwnerTable,
			Columns: []string{contributorrewardlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.OwnerTable,
			Columns: []string{contributorrewardlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.AccountTable,
			Columns: []string{contributorrewardlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.AccountTable,
			Columns: []string{contributorrewardlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contributorrewardlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContributorRewardLogUpdateOne is the builder for updating a single ContributorRewardLog entity.
type ContributorRewardLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContributorRewardLogMutation
}

// SetRequestID sets the "request_id" field.
func (_u *ContributorRewardLogUpdateOne) SetRequestID(v string) *ContributorRewardLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableRequestID(v *string) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ContributorRewardLogUpdateOne) SetAPIKeyID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableAPIKeyID(v *int64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *ContributorRewardLogUpdateOne) AddAPIKeyID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *ContributorRewardLogUpdateOne) SetOwnerUserID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableOwnerUserID(v *int64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (_u *ContributorRewardLogUpdateOne) SetConsumerUserID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.ResetConsumerUserID()
	_u.mutation.SetConsumerUserID(v)
	return _u
}

// SetNillableConsumerUserID sets the "consumer_user_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableConsumerUserID(v *int64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetConsumerUserID(*v)
	}
	return _u
}

// AddConsumerUserID adds value to the "consumer_user_id" field.
func (_u *ContributorRewardLogUpdateOne) AddConsumerUserID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.AddConsumerUserID(v)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *ContributorRewardLogUpdateOne) SetAccountID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableAccountID(v *int64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *ContributorRewardLogUpdateOne) SetGroupID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableGroupID(v *int64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *ContributorRewardLogUpdateOne) AddGroupID(v int64) *ContributorRewardLogUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// ClearGroupID clears the value of the "group_id" field.
func (_u *ContributorRewardLogUpdateOne) ClearGroupID() *ContributorRewardLogUpdateOne {
	_u.mutation.ClearGroupID()
	return _u
}

// SetTotalCost sets the "total_cost" field.
func (_u *ContributorRewardLogUpdateOne) SetTotalCost(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.ResetTotalCost()
	_u.mutation.SetTotalCost(v)
	return _u
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableTotalCost(v *float64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetTotalCost(*v)
	}
	return _u
}

// AddTotalCost adds value to the "total_cost" field.
func (_u *ContributorRewardLogUpdateOne) AddTotalCost(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.AddTotalCost(v)
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *ContributorRewardLogUpdateOne) SetActualCost(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableActualCost(v *float64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *ContributorRewardLogUpdateOne) AddActualCost(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (_u *ContributorRewardLogUpdateOne) SetRewardMultiplier(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.ResetRewardMultiplier()
	_u.mutation.SetRewardMultiplier(v)
	return _u
}

// SetNillableRewardMultiplier sets the "reward_multiplier" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableRewardMultiplier(v *float64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetRewardMultiplier(*v)
	}
	return _u
}

// AddRewardMultiplier adds value to the "reward_multiplier" field.
func (_u *ContributorRewardLogUpdateOne) AddRewardMultiplier(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.AddRewardMultiplier(v)
	return _u
}

// SetRewardAmount sets the "reward_amount" field.
func (_u *ContributorRewardLogUpdateOne) SetRewardAmount(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.ResetRewardAmount()
	_u.mutation.SetRewardAmount(v)
	return _u
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_u *ContributorRewardLogUpdateOne) SetNillableRewardAmount(v *float64) *ContributorRewardLogUpdateOne {
	if v != nil {
		_u.SetRewardAmount(*v)
	}
	return _u
}

// AddRewardAmount adds value to the "reward_amount" field.
func (_u *ContributorRewardLogUpdateOne) AddRewardAmount(v float64) *ContributorRewardLogUpdateOne {
	_u.mutation.AddRewardAmount(v)
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *ContributorRewardLogUpdateOne) SetOwnerID(id int64) *ContributorRewardLogUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *ContributorRewardLogUpdateOne) SetOwner(v *User) *ContributorRewardLogUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *ContributorRewardLogUpdateOne) SetAccount(v *Account) *ContributorRewardLogUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the ContributorRewardLogMutation object of the builder.
func (_u *ContributorRewardLogUpdateOne) Mutation() *ContributorRewardLogMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *ContributorRewardLogUpdateOne) ClearOwner() *ContributorRewardLogUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *ContributorRewardLogUpdateOne) ClearAccount() *ContributorRewardLogUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the ContributorRewardLogUpdate builder.
func (_u *ContributorRewardLogUpdateOne) Where(ps ...predicate.ContributorRewardLog) *ContributorRewardLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContributorRewardLogUpdateOne) Select(field string, fields ...string) *ContributorRewardLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ContributorRewardLog entity.
func (_u *ContributorRewardLogUpdateOne) Save(ctx context.Context) (*ContributorRewardLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContributorRewardLogUpdateOne) SaveX(ctx context.Context) *ContributorRewardLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContributorRewardLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContributorRewardLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContributorRewardLogUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := contributorrewardlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ContributorRewardLog.request_id": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ContributorRewardLog.owner"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ContributorRewardLog.account"`)
	}
	return nil
}

func (_u *ContributorRewardLogUpdateOne) sqlSave(ctx context.Context) (_node *ContributorRewardLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contributorrewardlog.Table, contributorrewardlog.Columns, sqlgraph.NewFieldSpec(contributorrewardlog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ContributorRewardLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contributorrewardlog.FieldID)
		for _, f := range fields {
			if !contributorrewardlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contributorrewardlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(contributorrewardlog.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(contributorrewardlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(contributorrewardlog.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ConsumerUserID(); ok {
		_spec.SetField(contributorrewardlog.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedConsumerUserID(); ok {
		_spec.AddField(contributorrewardlog.FieldConsumerUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(contributorrewardlog.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(contributorrewardlog.FieldGroupID, field.TypeInt64, value)
	}
	if _u.mutation.GroupIDCleared() {
		_spec.ClearField(contributorrewardlog.FieldGroupID, field.TypeInt64)
	}
	if value, ok := _u.mutation.TotalCost(); ok {
		_spec.SetField(contributorrewardlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedTotalCost(); ok {
		_spec.AddField(contributorrewardlog.FieldTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(contributorrewardlog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(contributorrewardlog.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardMultiplier(); ok {
		_spec.SetField(contributorrewardlog.FieldRewardMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardMultiplier(); ok {
		_spec.AddField(contributorrewardlog.FieldRewardMultiplier, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RewardAmount(); ok {
		_spec.SetField(contributorrewardlog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRewardAmount(); ok {
		_spec.AddField(contributorrewardlog.FieldRewardAmount, field.TypeFloat64, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.OwnerTable,
			Columns: []string{contributorrewardlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.OwnerTable,
			Columns: []string{contributorrewardlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.AccountTable,
			Columns: []string{contributorrewardlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.AccountTable,
			Columns: []string{contributorrewardlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ContributorRewardLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contributorrewardlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
