// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributorrewardlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ContributorRewardLog is the model entity for the ContributorRewardLog schema.
type ContributorRewardLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID int64 `json:"owner_user_id,omitempty"`
	// ConsumerUserID holds the value of the "consumer_user_id" field.
	ConsumerUserID int64 `json:"consumer_user_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// TotalCost holds the value of the "total_cost" field.
	TotalCost float64 `json:"total_cost,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost float64 `json:"actual_cost,omitempty"`
	// RewardMultiplier holds the value of the "reward_multiplier" field.
	RewardMultiplier float64 `json:"reward_multiplier,omitempty"`
	// RewardAmount holds the value of the "reward_amount" field.
	RewardAmount float64 `json:"reward_amount,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ContributorRewardLogQuery when eager-loading is set.
	Edges        ContributorRewardLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ContributorRewardLogEdges holds the relations/edges for other nodes in the graph.
type ContributorRewardLogEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContributorRewardLogEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ContributorRewardLogEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContributorRewardLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contributorrewardlog.FieldTotalCost, contributorrewardlog.FieldActualCost, contributorrewardlog.FieldRewardMultiplier, contributorrewardlog.FieldRewardAmount:
			values[i] = new(sql.NullFloat64)
		case contributorrewardlog.FieldID, contributorrewardlog.FieldAPIKeyID, contributorrewardlog.FieldOwnerUserID, contributorrewardlog.FieldConsumerUserID, contributorrewardlog.FieldAccountID, contributorrewardlog.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case contributorrewardlog.FieldRequestID:
			values[i] = new(sql.NullString)
		case contributorrewardlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContributorRewardLog fields.
func (_m *ContributorRewardLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contributorrewardlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case contributorrewardlog.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case contributorrewardlog.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case contributorrewardlog.FieldOwnerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value.Valid {
				_m.OwnerUserID = value.Int64
			}
		case contributorrewardlog.FieldConsumerUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consumer_user_id", values[i])
			} else if value.Valid {
				_m.ConsumerUserID = value.Int64
			}
		case contributorrewardlog.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case contributorrewardlog.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case contributorrewardlog.FieldTotalCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_cost", values[i])
			} else if value.Valid {
				_m.TotalCost = value.Float64
			}
		case contributorrewardlog.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = value.Float64
			}
		case contributorrewardlog.FieldRewardMultiplier:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_multiplier", values[i])
			} else if value.Valid {
				_m.RewardMultiplier = value.Float64
			}
		case contributorrewardlog.FieldRewardAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reward_amount", values[i])
			} else if value.Valid {
				_m.RewardAmount = value.Float64
			}
		case contributorrewardlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContributorRewardLog.
// This includes values selected through modifiers, order, etc.
func (_m *ContributorRewardLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the ContributorRewardLog entity.
func (_m *ContributorRewardLog) QueryOwner() *UserQuery {
	return NewContributorRewardLogClient(_m.config).QueryOwner(_m)
}

// QueryAccount queries the "account" edge of the ContributorRewardLog entity.
func (_m *ContributorRewardLog) QueryAccount() *AccountQuery {
	return NewContributorRewardLogClient(_m.config).QueryAccount(_m)
}

// Update returns a builder for updating this ContributorRewardLog.
// Note that you need to call ContributorRewardLog.Unwrap() before calling this method if this ContributorRewardLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ContributorRewardLog) Update() *ContributorRewardLogUpdateOne {
	return NewContributorRewardLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ContributorRewardLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ContributorRewardLog) Unwrap() *ContributorRewardLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContributorRewardLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ContributorRewardLog) String() string {
	var builder strings.Builder
	builder.WriteString("ContributorRewardLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	builder.WriteString("consumer_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsumerUserID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("total_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalCost))
	builder.WriteString(", ")
	builder.WriteString("actual_cost=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActualCost))
	builder.WriteString(", ")
	builder.WriteString("reward_multiplier=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardMultiplier))
	builder.WriteString(", ")
	builder.WriteString("reward_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RewardAmount))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContributorRewardLogs is a parsable slice of ContributorRewardLog.
type ContributorRewardLogs []*ContributorRewardLog
