// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/contributorrewardlog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ContributorRewardLogCreate is the builder for creating a ContributorRewardLog entity.
type ContributorRewardLogCreate struct {
	config
	mutation *ContributorRewardLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRequestID sets the "request_id" field.
func (_c *ContributorRewardLogCreate) SetRequestID(v string) *ContributorRewardLogCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ContributorRewardLogCreate) SetAPIKeyID(v int64) *ContributorRewardLogCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_c *ContributorRewardLogCreate) SetOwnerUserID(v int64) *ContributorRewardLogCreate {
	_c.mutation.SetOwnerUserID(v)
	return _c
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (_c *ContributorRewardLogCreate) SetConsumerUserID(v int64) *ContributorRewardLogCreate {
	_c.mutation.SetConsumerUserID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *ContributorRewardLogCreate) SetAccountID(v int64) *ContributorRewardLogCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *ContributorRewardLogCreate) SetGroupID(v int64) *ContributorRewardLogCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *ContributorRewardLogCreate) SetNillableGroupID(v *int64) *ContributorRewardLogCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetTotalCost sets the "total_cost" field.
func (_c *ContributorRewardLogCreate) SetTotalCost(v float64) *ContributorRewardLogCreate {
	_c.mutation.SetTotalCost(v)
	return _c
}

// SetNillableTotalCost sets the "total_cost" field if the given value is not nil.
func (_c *ContributorRewardLogCreate) SetNillableTotalCost(v *float64) *ContributorRewardLogCreate {
	if v != nil {
		_c.SetTotalCost(*v)
	}
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *ContributorRewardLogCreate) SetActualCost(v float64) *ContributorRewardLogCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_c *ContributorRewardLogCreate) SetNillableActualCost(v *float64) *ContributorRewardLogCreate {
	if v != nil {
		_c.SetActualCost(*v)
	}
	return _c
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (_c *ContributorRewardLogCreate) SetRewardMultiplier(v float64) *ContributorRewardLogCreate {
	_c.mutation.SetRewardMultiplier(v)
	return _c
}

// SetNillableRewardMultiplier sets the "reward_multiplier" field if the given value is not nil.
func (_c *ContributorRewardLogCreate) SetNillableRewardMultiplier(v *float64) *ContributorRewardLogCreate {
	if v != nil {
		_c.SetRewardMultiplier(*v)
	}
	return _c
}

// SetRewardAmount sets the "reward_amount" field.
func (_c *ContributorRewardLogCreate) SetRewardAmount(v float64) *ContributorRewardLogCreate {
	_c.mutation.SetRewardAmount(v)
	return _c
}

// SetNillableRewardAmount sets the "reward_amount" field if the given value is not nil.
func (_c *ContributorRewardLogCreate) SetNillableRewardAmount(v *float64) *ContributorRewardLogCreate {
	if v != nil {
		_c.SetRewardAmount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContributorRewardLogCreate) SetCreatedAt(v time.Time) *ContributorRewardLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContributorRewardLogCreate) SetNillableCreatedAt(v *time.Time) *ContributorRewardLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_c *ContributorRewardLogCreate) SetOwnerID(id int64) *ContributorRewardLogCreate {
	_c.mutation.SetOwnerID(id)
	return _c
}

// SetOwner sets the "owner" edge to the User entity.
func (_c *ContributorRewardLogCreate) SetOwner(v *User) *ContributorRewardLogCreate {
	return _c.SetOwnerID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *ContributorRewardLogCreate) SetAccount(v *Account) *ContributorRewardLogCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the ContributorRewardLogMutation object of the builder.
func (_c *ContributorRewardLogCreate) Mutation() *ContributorRewardLogMutation {
	return _c.mutation
}

// Save creates the ContributorRewardLog in the database.
func (_c *ContributorRewardLogCreate) Save(ctx context.Context) (*ContributorRewardLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContributorRewardLogCreate) SaveX(ctx context.Context) *ContributorRewardLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContributorRewardLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContributorRewardLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContributorRewardLogCreate) defaults() {
	if _, ok := _c.mutation.TotalCost(); !ok {
		v := contributorrewardlog.DefaultTotalCost
		_c.mutation.SetTotalCost(v)
	}
	if _, ok := _c.mutation.ActualCost(); !ok {
		v := contributorrewardlog.DefaultActualCost
		_c.mutation.SetActualCost(v)
	}
	if _, ok := _c.mutation.RewardMultiplier(); !ok {
		v := contributorrewardlog.DefaultRewardMultiplier
		_c.mutation.SetRewardMultiplier(v)
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		v := contributorrewardlog.DefaultRewardAmount
		_c.mutation.SetRewardAmount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contributorrewardlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContributorRewardLogCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "ContributorRewardLog.request_id"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := contributorrewardlog.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "ContributorRewardLog.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "ContributorRewardLog.api_key_id"`)}
	}
	if _, ok := _c.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "ContributorRewardLog.owner_user_id"`)}
	}
	if _, ok := _c.mutation.ConsumerUserID(); !ok {
		return &ValidationError{Name: "consumer_user_id", err: errors.New(`ent: missing required field "ContributorRewardLog.consumer_user_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "ContributorRewardLog.account_id"`)}
	}
	if _, ok := _c.mutation.TotalCost(); !ok {
		return &ValidationError{Name: "total_cost", err: errors.New(`ent: missing required field "ContributorRewardLog.total_cost"`)}
	}
	if _, ok := _c.mutation.ActualCost(); !ok {
		return &ValidationError{Name: "actual_cost", err: errors.New(`ent: missing required field "ContributorRewardLog.actual_cost"`)}
	}
	if _, ok := _c.mutation.RewardMultiplier(); !ok {
		return &ValidationError{Name: "reward_multiplier", err: errors.New(`ent: missing required field "ContributorRewardLog.reward_multiplier"`)}
	}
	if _, ok := _c.mutation.RewardAmount(); !ok {
		return &ValidationError{Name: "reward_amount", err: errors.New(`ent: missing required field "ContributorRewardLog.reward_amount"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ContributorRewardLog.created_at"`)}
	}
	if len(_c.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "ContributorRewardLog.owner"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "ContributorRewardLog.account"`)}
	}
	return nil
}

func (_c *ContributorRewardLogCreate) sqlSave(ctx context.Context) (*ContributorRewardLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContributorRewardLogCreate) createSpec() (*ContributorRewardLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ContributorRewardLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contributorrewardlog.Table, sqlgraph.NewFieldSpec(contributorrewardlog.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(contributorrewardlog.FieldRequestID, field.TypeString, value)
		_node.RequestID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(contributorrewardlog.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.ConsumerUserID(); ok {
		_spec.SetField(contributorrewardlog.FieldConsumerUserID, field.TypeInt64, value)
		_node.ConsumerUserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(contributorrewardlog.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.TotalCost(); ok {
		_spec.SetField(contributorrewardlog.FieldTotalCost, field.TypeFloat64, value)
		_node.TotalCost = value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(contributorrewardlog.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = value
	}
	if value, ok := _c.mutation.RewardMultiplier(); ok {
		_spec.SetField(contributorrewardlog.FieldRewardMultiplier, field.TypeFloat64, value)
		_node.RewardMultiplier = value
	}
	if value, ok := _c.mutation.RewardAmount(); ok {
		_spec.SetField(contributorrewardlog.FieldRewardAmount, field.TypeFloat64, value)
		_node.RewardAmount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contributorrewardlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.OwnerTable,
			Columns: []string{contributorrewardlog.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   contributorrewardlog.AccountTable,
			Columns: []string{contributorrewardlog.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContributorRewardLog.Create().
//		SetRequestID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContributorRewardLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContributorRewardLogCreate) OnConflict(opts ...sql.ConflictOption) *ContributorRewardLogUpsertOne {
	_c.conflict = opts
	return &ContributorRewardLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContributorRewardLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContributorRewardLogCreate) OnConflictColumns(columns ...string) *ContributorRewardLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContributorRewardLogUpsertOne{
		create: _c,
	}
}

type (
	// ContributorRewardLogUpsertOne is the builder for "upsert"-ing
	//  one ContributorRewardLog node.
	ContributorRewardLogUpsertOne struct {
		create *ContributorRewardLogCreate
	}

	// ContributorRewardLogUpsert is the "OnConflict" setter.
	ContributorRewardLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetRequestID sets the "request_id" field.
func (u *ContributorRewardLogUpsert) SetRequestID(v string) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateRequestID() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldRequestID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ContributorRewardLogUpsert) SetAPIKeyID(v int64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateAPIKeyID() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ContributorRewardLogUpsert) AddAPIKeyID(v int64) *ContributorRewardLogUpsert {
	u.Add(contributorrewardlog.FieldAPIKeyID, v)
	return u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ContributorRewardLogUpsert) SetOwnerUserID(v int64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldOwnerUserID, v)
	return u
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateOwnerUserID() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldOwnerUserID)
	return u
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (u *ContributorRewardLogUpsert) SetConsumerUserID(v int64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldConsumerUserID, v)
	return u
}

// UpdateConsumerUserID sets the "consumer_user_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateConsumerUserID() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldConsumerUserID)
	return u
}

// AddConsumerUserID adds v to the "consumer_user_id" field.
func (u *ContributorRewardLogUpsert) AddConsumerUserID(v int64) *ContributorRewardLogUpsert {
	u.Add(contributorrewardlog.FieldConsumerUserID, v)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *ContributorRewardLogUpsert) SetAccountID(v int64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateAccountID() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldAccountID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *ContributorRewardLogUpsert) SetGroupID(v int64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateGroupID() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *ContributorRewardLogUpsert) AddGroupID(v int64) *ContributorRewardLogUpsert {
	u.Add(contributorrewardlog.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ContributorRewardLogUpsert) ClearGroupID() *ContributorRewardLogUpsert {
	u.SetNull(contributorrewardlog.FieldGroupID)
	return u
}

// SetTotalCost sets the "total_cost" field.
func (u *ContributorRewardLogUpsert) SetTotalCost(v float64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldTotalCost, v)
	return u
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateTotalCost() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldTotalCost)
	return u
}

// AddTotalCost adds v to the "total_cost" field.
func (u *ContributorRewardLogUpsert) AddTotalCost(v float64) *ContributorRewardLogUpsert {
	u.Add(contributorrewardlog.FieldTotalCost, v)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *ContributorRewardLogUpsert) SetActualCost(v float64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateActualCost() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *ContributorRewardLogUpsert) AddActualCost(v float64) *ContributorRewardLogUpsert {
	u.Add(contributorrewardlog.FieldActualCost, v)
	return u
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (u *ContributorRewardLogUpsert) SetRewardMultiplier(v float64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldRewardMultiplier, v)
	return u
}

// UpdateRewardMultiplier sets the "reward_multiplier" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateRewardMultiplier() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldRewardMultiplier)
	return u
}

// AddRewardMultiplier adds v to the "reward_multiplier" field.
func (u *ContributorRewardLogUpsert) AddRewardMultiplier(v float64) *ContributorRewardLogUpsert {
	u.Add(contributorrewardlog.FieldRewardMultiplier, v)
	return u
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ContributorRewardLogUpsert) SetRewardAmount(v float64) *ContributorRewardLogUpsert {
	u.Set(contributorrewardlog.FieldRewardAmount, v)
	return u
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ContributorRewardLogUpsert) UpdateRewardAmount() *ContributorRewardLogUpsert {
	u.SetExcluded(contributorrewardlog.FieldRewardAmount)
	return u
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ContributorRewardLogUpsert) AddRewardAmount(v float64) *ContributorRewardLogUpsert {
	u.Add(contributorrewardlog.FieldRewardAmount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ContributorRewardLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContributorRewardLogUpsertOne) UpdateNewValues() *ContributorRewardLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(contributorrewardlog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContributorRewardLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ContributorRewardLogUpsertOne) Ignore() *ContributorRewardLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContributorRewardLogUpsertOne) DoNothing() *ContributorRewardLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContributorRewardLogCreate.OnConflict
// documentation for more info.
func (u *ContributorRewardLogUpsertOne) Update(set func(*ContributorRewardLogUpsert)) *ContributorRewardLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContributorRewardLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *ContributorRewardLogUpsertOne) SetRequestID(v string) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateRequestID() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ContributorRewardLogUpsertOne) SetAPIKeyID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ContributorRewardLogUpsertOne) AddAPIKeyID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateAPIKeyID() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ContributorRewardLogUpsertOne) SetOwnerUserID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateOwnerUserID() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (u *ContributorRewardLogUpsertOne) SetConsumerUserID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetConsumerUserID(v)
	})
}

// AddConsumerUserID adds v to the "consumer_user_id" field.
func (u *ContributorRewardLogUpsertOne) AddConsumerUserID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddConsumerUserID(v)
	})
}

// UpdateConsumerUserID sets the "consumer_user_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateConsumerUserID() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateConsumerUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ContributorRewardLogUpsertOne) SetAccountID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateAccountID() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ContributorRewardLogUpsertOne) SetGroupID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ContributorRewardLogUpsertOne) AddGroupID(v int64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateGroupID() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ContributorRewardLogUpsertOne) ClearGroupID() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.ClearGroupID()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *ContributorRewardLogUpsertOne) SetTotalCost(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *ContributorRewardLogUpsertOne) AddTotalCost(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateTotalCost() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateTotalCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *ContributorRewardLogUpsertOne) SetActualCost(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *ContributorRewardLogUpsertOne) AddActualCost(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateActualCost() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateActualCost()
	})
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (u *ContributorRewardLogUpsertOne) SetRewardMultiplier(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetRewardMultiplier(v)
	})
}

// AddRewardMultiplier adds v to the "reward_multiplier" field.
func (u *ContributorRewardLogUpsertOne) AddRewardMultiplier(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddRewardMultiplier(v)
	})
}

// UpdateRewardMultiplier sets the "reward_multiplier" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateRewardMultiplier() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateRewardMultiplier()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ContributorRewardLogUpsertOne) SetRewardAmount(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ContributorRewardLogUpsertOne) AddRewardAmount(v float64) *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertOne) UpdateRewardAmount() *ContributorRewardLogUpsertOne {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateRewardAmount()
	})
}

// Exec executes the query.
func (u *ContributorRewardLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContributorRewardLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContributorRewardLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ContributorRewardLogUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ContributorRewardLogUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ContributorRewardLogCreateBulk is the builder for creating many ContributorRewardLog entities in bulk.
type ContributorRewardLogCreateBulk struct {
	config
	err      error
	builders []*ContributorRewardLogCreate
	conflict []sql.ConflictOption
}

// Save creates the ContributorRewardLog entities in the database.
func (_c *ContributorRewardLogCreateBulk) Save(ctx context.Context) ([]*ContributorRewardLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContributorRewardLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContributorRewardLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContributorRewardLogCreateBulk) SaveX(ctx context.Context) []*ContributorRewardLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContributorRewardLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContributorRewardLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ContributorRewardLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ContributorRewardLogUpsert) {
//			SetRequestID(v+v).
//		}).
//		Exec(ctx)
func (_c *ContributorRewardLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ContributorRewardLogUpsertBulk {
	_c.conflict = opts
	return &ContributorRewardLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ContributorRewardLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ContributorRewardLogCreateBulk) OnConflictColumns(columns ...string) *ContributorRewardLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ContributorRewardLogUpsertBulk{
		create: _c,
	}
}

// ContributorRewardLogUpsertBulk is the builder for "upsert"-ing
// a bulk of ContributorRewardLog nodes.
type ContributorRewardLogUpsertBulk struct {
	create *ContributorRewardLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ContributorRewardLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ContributorRewardLogUpsertBulk) UpdateNewValues() *ContributorRewardLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(contributorrewardlog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ContributorRewardLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ContributorRewardLogUpsertBulk) Ignore() *ContributorRewardLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ContributorRewardLogUpsertBulk) DoNothing() *ContributorRewardLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ContributorRewardLogCreateBulk.OnConflict
// documentation for more info.
func (u *ContributorRewardLogUpsertBulk) Update(set func(*ContributorRewardLogUpsert)) *ContributorRewardLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ContributorRewardLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetRequestID sets the "request_id" field.
func (u *ContributorRewardLogUpsertBulk) SetRequestID(v string) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateRequestID() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateRequestID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ContributorRewardLogUpsertBulk) SetAPIKeyID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *ContributorRewardLogUpsertBulk) AddAPIKeyID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateAPIKeyID() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetOwnerUserID sets the "owner_user_id" field.
func (u *ContributorRewardLogUpsertBulk) SetOwnerUserID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetOwnerUserID(v)
	})
}

// UpdateOwnerUserID sets the "owner_user_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateOwnerUserID() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateOwnerUserID()
	})
}

// SetConsumerUserID sets the "consumer_user_id" field.
func (u *ContributorRewardLogUpsertBulk) SetConsumerUserID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetConsumerUserID(v)
	})
}

// AddConsumerUserID adds v to the "consumer_user_id" field.
func (u *ContributorRewardLogUpsertBulk) AddConsumerUserID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddConsumerUserID(v)
	})
}

// UpdateConsumerUserID sets the "consumer_user_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateConsumerUserID() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateConsumerUserID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *ContributorRewardLogUpsertBulk) SetAccountID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateAccountID() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *ContributorRewardLogUpsertBulk) SetGroupID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *ContributorRewardLogUpsertBulk) AddGroupID(v int64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateGroupID() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *ContributorRewardLogUpsertBulk) ClearGroupID() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.ClearGroupID()
	})
}

// SetTotalCost sets the "total_cost" field.
func (u *ContributorRewardLogUpsertBulk) SetTotalCost(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetTotalCost(v)
	})
}

// AddTotalCost adds v to the "total_cost" field.
func (u *ContributorRewardLogUpsertBulk) AddTotalCost(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddTotalCost(v)
	})
}

// UpdateTotalCost sets the "total_cost" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateTotalCost() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateTotalCost()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *ContributorRewardLogUpsertBulk) SetActualCost(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *ContributorRewardLogUpsertBulk) AddActualCost(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateActualCost() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateActualCost()
	})
}

// SetRewardMultiplier sets the "reward_multiplier" field.
func (u *ContributorRewardLogUpsertBulk) SetRewardMultiplier(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetRewardMultiplier(v)
	})
}

// AddRewardMultiplier adds v to the "reward_multiplier" field.
func (u *ContributorRewardLogUpsertBulk) AddRewardMultiplier(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddRewardMultiplier(v)
	})
}

// UpdateRewardMultiplier sets the "reward_multiplier" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateRewardMultiplier() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateRewardMultiplier()
	})
}

// SetRewardAmount sets the "reward_amount" field.
func (u *ContributorRewardLogUpsertBulk) SetRewardAmount(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.SetRewardAmount(v)
	})
}

// AddRewardAmount adds v to the "reward_amount" field.
func (u *ContributorRewardLogUpsertBulk) AddRewardAmount(v float64) *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.AddRewardAmount(v)
	})
}

// UpdateRewardAmount sets the "reward_amount" field to the value that was provided on create.
func (u *ContributorRewardLogUpsertBulk) UpdateRewardAmount() *ContributorRewardLogUpsertBulk {
	return u.Update(func(s *ContributorRewardLogUpsert) {
		s.UpdateRewardAmount()
	})
}

// Exec executes the query.
func (u *ContributorRewardLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ContributorRewardLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ContributorRewardLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ContributorRewardLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
