// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/contributorrewardlog"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ContributorRewardLogDelete is the builder for deleting a ContributorRewardLog entity.
type ContributorRewardLogDelete struct {
	config
	hooks    []Hook
	mutation *ContributorRewardLogMutation
}

// Where appends a list predicates to the ContributorRewardLogDelete builder.
func (_d *ContributorRewardLogDelete) Where(ps ...predicate.ContributorRewardLog) *ContributorRewardLogDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ContributorRewardLogDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContributorRewardLogDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ContributorRewardLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contributorrewardlog.Table, sqlgraph.NewFieldSpec(contributorrewardlog.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ContributorRewardLogDeleteOne is the builder for deleting a single ContributorRewardLog entity.
type ContributorRewardLogDeleteOne struct {
	_d *ContributorRewardLogDelete
}

// Where appends a list predicates to the ContributorRewardLogDelete builder.
func (_d *ContributorRewardLogDeleteOne) Where(ps ...predicate.ContributorRewardLog) *ContributorRewardLogDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ContributorRewardLogDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contributorrewardlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ContributorRewardLogDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
