// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/redeemcode"
	"github.com/Wei-Shaw/sub2api/ent/redeemcodeusage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// RedeemCodeUsageCreate is the builder for creating a RedeemCodeUsage entity.
type RedeemCodeUsageCreate struct {
	config
	mutation *RedeemCodeUsageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (_c *RedeemCodeUsageCreate) SetRedeemCodeID(v int64) *RedeemCodeUsageCreate {
	_c.mutation.SetRedeemCodeID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RedeemCodeUsageCreate) SetUserID(v int64) *RedeemCodeUsageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *RedeemCodeUsageCreate) SetValue(v float64) *RedeemCodeUsageCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *RedeemCodeUsageCreate) SetNillableValue(v *float64) *RedeemCodeUsageCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RedeemCodeUsageCreate) SetCreatedAt(v time.Time) *RedeemCodeUsageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RedeemCodeUsageCreate) SetNillableCreatedAt(v *time.Time) *RedeemCodeUsageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetRedeemCode sets the "redeem_code" edge to the RedeemCode entity.
func (_c *RedeemCodeUsageCreate) SetRedeemCode(v *RedeemCode) *RedeemCodeUsageCreate {
	return _c.SetRedeemCodeID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *RedeemCodeUsageCreate) SetUser(v *User) *RedeemCodeUsageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the RedeemCodeUsageMutation object of the builder.
func (_c *RedeemCodeUsageCreate) Mutation() *RedeemCodeUsageMutation {
	return _c.mutation
}

// Save creates the RedeemCodeUsage in the database.
func (_c *RedeemCodeUsageCreate) Save(ctx context.Context) (*RedeemCodeUsage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RedeemCodeUsageCreate) SaveX(ctx context.Context) *RedeemCodeUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeUsageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeUsageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RedeemCodeUsageCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := redeemcodeusage.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := redeemcodeusage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RedeemCodeUsageCreate) check() error {
	if _, ok := _c.mutation.RedeemCodeID(); !ok {
		return &ValidationError{Name: "redeem_code_id", err: errors.New(`ent: missing required field "RedeemCodeUsage.redeem_code_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RedeemCodeUsage.user_id"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "RedeemCodeUsage.value"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RedeemCodeUsage.created_at"`)}
	}
	if len(_c.mutation.RedeemCodeIDs()) == 0 {
		return &ValidationError{Name: "redeem_code", err: errors.New(`ent: missing required edge "RedeemCodeUsage.redeem_code"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "RedeemCodeUsage.user"`)}
	}
	return nil
}

func (_c *RedeemCodeUsageCreate) sqlSave(ctx context.Context) (*RedeemCodeUsage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RedeemCodeUsageCreate) createSpec() (*RedeemCodeUsage, *sqlgraph.CreateSpec) {
	var (
		_node = &RedeemCodeUsage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(redeemcodeusage.Table, sqlgraph.NewFieldSpec(redeemcodeusage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(redeemcodeusage.FieldValue, field.TypeFloat64, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(redeemcodeusage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RedeemCodeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.RedeemCodeTable,
			Columns: []string{redeemcodeusage.RedeemCodeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(redeemcode.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RedeemCodeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   redeemcodeusage.UserTable,
			Columns: []string{redeemcodeusage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeUsage.Create().
//		SetRedeemCodeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeUsageUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeUsageCreate) OnConflict(opts ...sql.ConflictOption) *RedeemCodeUsageUpsertOne {
	_c.conflict = opts
	return &RedeemCodeUsageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeUsageCreate) OnConflictColumns(columns ...string) *RedeemCodeUsageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeUsageUpsertOne{
		create: _c,
	}
}

type (
	// RedeemCodeUsageUpsertOne is the builder for "upsert"-ing
	//  one RedeemCodeUsage node.
	RedeemCodeUsageUpsertOne struct {
		create *RedeemCodeUsageCreate
	}

	// RedeemCodeUsageUpsert is the "OnConflict" setter.
	RedeemCodeUsageUpsert struct {
		*sql.UpdateSet
	}
)

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeUsageUpsert) SetRedeemCodeID(v int64) *RedeemCodeUsageUpsert {
	u.Set(redeemcodeusage.FieldRedeemCodeID, v)
	return u
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsert) UpdateRedeemCodeID() *RedeemCodeUsageUpsert {
	u.SetExcluded(redeemcodeusage.FieldRedeemCodeID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeUsageUpsert) SetUserID(v int64) *RedeemCodeUsageUpsert {
	u.Set(redeemcodeusage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsert) UpdateUserID() *RedeemCodeUsageUpsert {
	u.SetExcluded(redeemcodeusage.FieldUserID)
	return u
}

// SetValue sets the "value" field.
func (u *RedeemCodeUsageUpsert) SetValue(v float64) *RedeemCodeUsageUpsert {
	u.Set(redeemcodeusage.FieldValue, v)
	return u
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsert) UpdateValue() *RedeemCodeUsageUpsert {
	u.SetExcluded(redeemcodeusage.FieldValue)
	return u
}

// AddValue adds v to the "value" field.
func (u *RedeemCodeUsageUpsert) AddValue(v float64) *RedeemCodeUsageUpsert {
	u.Add(redeemcodeusage.FieldValue, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RedeemCodeUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeUsageUpsertOne) UpdateNewValues() *RedeemCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(redeemcodeusage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeUsage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RedeemCodeUsageUpsertOne) Ignore() *RedeemCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeUsageUpsertOne) DoNothing() *RedeemCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeUsageCreate.OnConflict
// documentation for more info.
func (u *RedeemCodeUsageUpsertOne) Update(set func(*RedeemCodeUsageUpsert)) *RedeemCodeUsageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeUsageUpsertOne) SetRedeemCodeID(v int64) *RedeemCodeUsageUpsertOne {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsertOne) UpdateRedeemCodeID() *RedeemCodeUsageUpsertOne {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeUsageUpsertOne) SetUserID(v int64) *RedeemCodeUsageUpsertOne {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsertOne) UpdateUserID() *RedeemCodeUsageUpsertOne {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetValue sets the "value" field.
func (u *RedeemCodeUsageUpsertOne) SetValue(v float64) *RedeemCodeUsageUpsertOne {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *RedeemCodeUsageUpsertOne) AddValue(v float64) *RedeemCodeUsageUpsertOne {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsertOne) UpdateValue() *RedeemCodeUsageUpsertOne {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *RedeemCodeUsageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeUsageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeUsageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RedeemCodeUsageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RedeemCodeUsageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RedeemCodeUsageCreateBulk is the builder for creating many RedeemCodeUsage entities in bulk.
type RedeemCodeUsageCreateBulk struct {
	config
	err      error
	builders []*RedeemCodeUsageCreate
	conflict []sql.ConflictOption
}

// Save creates the RedeemCodeUsage entities in the database.
func (_c *RedeemCodeUsageCreateBulk) Save(ctx context.Context) ([]*RedeemCodeUsage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RedeemCodeUsage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RedeemCodeUsageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RedeemCodeUsageCreateBulk) SaveX(ctx context.Context) []*RedeemCodeUsage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RedeemCodeUsageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RedeemCodeUsageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RedeemCodeUsage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RedeemCodeUsageUpsert) {
//			SetRedeemCodeID(v+v).
//		}).
//		Exec(ctx)
func (_c *RedeemCodeUsageCreateBulk) OnConflict(opts ...sql.ConflictOption) *RedeemCodeUsageUpsertBulk {
	_c.conflict = opts
	return &RedeemCodeUsageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RedeemCodeUsage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RedeemCodeUsageCreateBulk) OnConflictColumns(columns ...string) *RedeemCodeUsageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RedeemCodeUsageUpsertBulk{
		create: _c,
	}
}

// RedeemCodeUsageUpsertBulk is the builder for "upsert"-ing
// a bulk of RedeemCodeUsage nodes.
type RedeemCodeUsageUpsertBulk struct {
	create *RedeemCodeUsageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RedeemCodeUsage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RedeemCodeUsageUpsertBulk) UpdateNewValues() *RedeemCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(redeemcodeusage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RedeemCodeUsage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RedeemCodeUsageUpsertBulk) Ignore() *RedeemCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RedeemCodeUsageUpsertBulk) DoNothing() *RedeemCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RedeemCodeUsageCreateBulk.OnConflict
// documentation for more info.
func (u *RedeemCodeUsageUpsertBulk) Update(set func(*RedeemCodeUsageUpsert)) *RedeemCodeUsageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RedeemCodeUsageUpsert{UpdateSet: update})
	}))
	return u
}

// SetRedeemCodeID sets the "redeem_code_id" field.
func (u *RedeemCodeUsageUpsertBulk) SetRedeemCodeID(v int64) *RedeemCodeUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.SetRedeemCodeID(v)
	})
}

// UpdateRedeemCodeID sets the "redeem_code_id" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsertBulk) UpdateRedeemCodeID() *RedeemCodeUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.UpdateRedeemCodeID()
	})
}

// SetUserID sets the "user_id" field.
func (u *RedeemCodeUsageUpsertBulk) SetUserID(v int64) *RedeemCodeUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsertBulk) UpdateUserID() *RedeemCodeUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.UpdateUserID()
	})
}

// SetValue sets the "value" field.
func (u *RedeemCodeUsageUpsertBulk) SetValue(v float64) *RedeemCodeUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.SetValue(v)
	})
}

// AddValue adds v to the "value" field.
func (u *RedeemCodeUsageUpsertBulk) AddValue(v float64) *RedeemCodeUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.AddValue(v)
	})
}

// UpdateValue sets the "value" field to the value that was provided on create.
func (u *RedeemCodeUsageUpsertBulk) UpdateValue() *RedeemCodeUsageUpsertBulk {
	return u.Update(func(s *RedeemCodeUsageUpsert) {
		s.UpdateValue()
	})
}

// Exec executes the query.
func (u *RedeemCodeUsageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RedeemCodeUsageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RedeemCodeUsageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RedeemCodeUsageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
