// Code generated by ent, DO NOT EDIT.

package contributorrewardlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldRequestID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// OwnerUserID applies equality check predicate on the "owner_user_id" field. It's identical to OwnerUserIDEQ.
func OwnerUserID(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldOwnerUserID, v))
}

// ConsumerUserID applies equality check predicate on the "consumer_user_id" field. It's identical to ConsumerUserIDEQ.
func ConsumerUserID(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldConsumerUserID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldAccountID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldGroupID, v))
}

// TotalCost applies equality check predicate on the "total_cost" field. It's identical to TotalCostEQ.
func TotalCost(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldTotalCost, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldActualCost, v))
}

// RewardMultiplier applies equality check predicate on the "reward_multiplier" field. It's identical to RewardMultiplierEQ.
func RewardMultiplier(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldRewardMultiplier, v))
}

// RewardAmount applies equality check predicate on the "reward_amount" field. It's identical to RewardAmountEQ.
func RewardAmount(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldRewardAmount, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldCreatedAt, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldContainsFold(FieldRequestID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldAPIKeyID, v))
}

// OwnerUserIDEQ applies the EQ predicate on the "owner_user_id" field.
func OwnerUserIDEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldOwnerUserID, v))
}

// OwnerUserIDNEQ applies the NEQ predicate on the "owner_user_id" field.
func OwnerUserIDNEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldOwnerUserID, v))
}

// OwnerUserIDIn applies the In predicate on the "owner_user_id" field.
func OwnerUserIDIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldOwnerUserID, vs...))
}

// OwnerUserIDNotIn applies the NotIn predicate on the "owner_user_id" field.
func OwnerUserIDNotIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldOwnerUserID, vs...))
}

// ConsumerUserIDEQ applies the EQ predicate on the "consumer_user_id" field.
func ConsumerUserIDEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldConsumerUserID, v))
}

// ConsumerUserIDNEQ applies the NEQ predicate on the "consumer_user_id" field.
func ConsumerUserIDNEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldConsumerUserID, v))
}

// ConsumerUserIDIn applies the In predicate on the "consumer_user_id" field.
func ConsumerUserIDIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldConsumerUserID, vs...))
}

// ConsumerUserIDNotIn applies the NotIn predicate on the "consumer_user_id" field.
func ConsumerUserIDNotIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldConsumerUserID, vs...))
}

// ConsumerUserIDGT applies the GT predicate on the "consumer_user_id" field.
func ConsumerUserIDGT(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldConsumerUserID, v))
}

// ConsumerUserIDGTE applies the GTE predicate on the "consumer_user_id" field.
func ConsumerUserIDGTE(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldConsumerUserID, v))
}

// ConsumerUserIDLT applies the LT predicate on the "consumer_user_id" field.
func ConsumerUserIDLT(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldConsumerUserID, v))
}

// ConsumerUserIDLTE applies the LTE predicate on the "consumer_user_id" field.
func ConsumerUserIDLTE(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldConsumerUserID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldAccountID, vs...))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotNull(FieldGroupID))
}

// TotalCostEQ applies the EQ predicate on the "total_cost" field.
func TotalCostEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldTotalCost, v))
}

// TotalCostNEQ applies the NEQ predicate on the "total_cost" field.
func TotalCostNEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldTotalCost, v))
}

// TotalCostIn applies the In predicate on the "total_cost" field.
func TotalCostIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldTotalCost, vs...))
}

// TotalCostNotIn applies the NotIn predicate on the "total_cost" field.
func TotalCostNotIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldTotalCost, vs...))
}

// TotalCostGT applies the GT predicate on the "total_cost" field.
func TotalCostGT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldTotalCost, v))
}

// TotalCostGTE applies the GTE predicate on the "total_cost" field.
func TotalCostGTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldTotalCost, v))
}

// TotalCostLT applies the LT predicate on the "total_cost" field.
func TotalCostLT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldTotalCost, v))
}

// TotalCostLTE applies the LTE predicate on the "total_cost" field.
func TotalCostLTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldTotalCost, v))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldActualCost, v))
}

// RewardMultiplierEQ applies the EQ predicate on the "reward_multiplier" field.
func RewardMultiplierEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldRewardMultiplier, v))
}

// RewardMultiplierNEQ applies the NEQ predicate on the "reward_multiplier" field.
func RewardMultiplierNEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldRewardMultiplier, v))
}

// RewardMultiplierIn applies the In predicate on the "reward_multiplier" field.
func RewardMultiplierIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldRewardMultiplier, vs...))
}

// RewardMultiplierNotIn applies the NotIn predicate on the "reward_multiplier" field.
func RewardMultiplierNotIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldRewardMultiplier, vs...))
}

// RewardMultiplierGT applies the GT predicate on the "reward_multiplier" field.
func RewardMultiplierGT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldRewardMultiplier, v))
}

// RewardMultiplierGTE applies the GTE predicate on the "reward_multiplier" field.
func RewardMultiplierGTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldRewardMultiplier, v))
}

// RewardMultiplierLT applies the LT predicate on the "reward_multiplier" field.
func RewardMultiplierLT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldRewardMultiplier, v))
}

// RewardMultiplierLTE applies the LTE predicate on the "reward_multiplier" field.
func RewardMultiplierLTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldRewardMultiplier, v))
}

// RewardAmountEQ applies the EQ predicate on the "reward_amount" field.
func RewardAmountEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldRewardAmount, v))
}

// RewardAmountNEQ applies the NEQ predicate on the "reward_amount" field.
func RewardAmountNEQ(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldRewardAmount, v))
}

// RewardAmountIn applies the In predicate on the "reward_amount" field.
func RewardAmountIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldRewardAmount, vs...))
}

// RewardAmountNotIn applies the NotIn predicate on the "reward_amount" field.
func RewardAmountNotIn(vs ...float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldRewardAmount, vs...))
}

// RewardAmountGT applies the GT predicate on the "reward_amount" field.
func RewardAmountGT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldRewardAmount, v))
}

// RewardAmountGTE applies the GTE predicate on the "reward_amount" field.
func RewardAmountGTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldRewardAmount, v))
}

// RewardAmountLT applies the LT predicate on the "reward_amount" field.
func RewardAmountLT(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldRewardAmount, v))
}

// RewardAmountLTE applies the LTE predicate on the "reward_amount" field.
func RewardAmountLTE(v float64) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldRewardAmount, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.FieldLTE(FieldCreatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.User) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ContributorRewardLog) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ContributorRewardLog) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ContributorRewardLog) predicate.ContributorRewardLog {
	return predicate.ContributorRewardLog(sql.NotPredicates(p))
}
